import turtle
wn=turtle.Screen()
wn.bgcolor("lightpink")
mariam=turtle.Turtle()
mariam.speed(1)
mariam.right(90)
mariam.forward(50)
mariam.left(90)
mariam.forward(90)
mariam.left(90)
mariam.forward(50)
mariam.left(90)
mariam.forward(90)
mariam.left(90)
wn.exitonclick()